config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get "users" => "users#index" 
  get "users/:id" => "users#show", as: :user
  get "signup" => "users#new"
  post "users" => "users#create"
  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update" 

  get "login" => "sessions#new" 
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get 'posts/' => 'posts#index'
  get 'posts/new' => 'posts#new', as: :new_post
  get 'posts/:id' => 'posts#show', as: :post
  post 'posts/' => 'posts#create'
  get 'posts/:id/edit' => 'posts#edit', as: :edit_post
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#destroy'

  post 'post/:id/comments' => 'comments#create', as: :post_comments
  delete 'comments/:id' => 'comments#destroy', as: :delete_comment

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy

	has_attached_file :image, styles: { :large => "600x600", :medium => "300x300", :thumb => "150x150#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
	
 	
	
	before_save :format_user_input

	attr_reader :password

	def password=(unencrypted_password)
		unless unencrypted_password.empty?
			@password = unencrypted_password
			self.password_digest = BCrypt::Password.create(unencrypted_password)
		end
	end 

	def authenticate(unencrypted_password)
		if BCrypt::Password.new(self.password_digest) == unencrypted_password
			return self
		else
			return false
		end
	end
	
	def format_user_input
    	self.name = self.name.titleize
    	self.email = self.email.downcase
  	end

	
	#validations
  validates :name, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  
  has_secure_password
  validates :password, presence: true, confirmation: true, length: {in: 6..20}, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  include SessionsHelper

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorized?
    if current_user == User.find(params[:id])
      @user = User.find(params[:id])
    else
      flash[:error] = "You are not authorized to view this page!"
      redirect_to posts_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @post = Post.find(params[:id])
    @comment = @post.comments.new(params.require(:comment).permit(:description))
    @comment.user_id = current_user.id
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @comment.destroy
  	redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all.order("created_at DESC")
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
		@comment = Comment.new
	end

	def create
		# @post = Post.new(post_params)
		# @post.user_id = current_user.id

		@user = current_user
		@post = @user.posts.new(post_params)

		if @post.valid? 
			if @post.save
				redirect_to post_path(@post)
			else
				render :new
			end
		else
			redirect_to new_post_path
		end
	end

	def edit
		@post = Post.find(params[:id])
			unless current_user.id == @post.user_id
				redirect_to post_path
			end
	end

	def update
		@post = Post.find(params[:id])	
			if @post.valid?
				if @post.update(post_params)
					redirect_to posts_path
				else
					render :edit
				end
			else
				redirect_to edit_post_path
			end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body, :image)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email])

    if user && user.authenticate(params[:login][:password]) 
      session[:user_id] = user.id.to_s
      redirect_to posts_path
    else
      flash.now[:error] = "Your email address or password is incorrect."
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :require_login, except: [:new, :create]
	
	def index
		@users = User.all
	end

  def new
		@user = User.new
  end

  def create
		@user = User.new(user_params)

		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to posts_path
		else
			render :new
		end
	end

	def edit
		authorized?
	end

	def update
		@user = User.find(params[:id])
		
		if @user.update_attributes(user_params)
			redirect_to edit_user_path(current_user)
		else
			render 'edit'
		end
	end

	private
	
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to acceess that page!"
      redirect_to login_path
    end
  end
end
# end of controller

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:user_id] != nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarForum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <% if logged_in? %>
      <p>Logged in as: <%= current_user.name %> | <%= link_to "Edit", edit_user_path(current_user) %> | <%= link_to 'Log Out', logout_path, method: :delete %> </p>
    <% else %>
      <div>
        <%= link_to 'Log In', login_path %> | <%= link_to 'Sign up', signup_path %>
      </div>
    <% end %>

    <!-- begin flash messages -->
    <% if flash[:welcome] %>
        <h4 class="bg-success flash"><%= flash[:welcome] %></h4>
    <% end %>

    <% if flash[:error] %>
        <h4 class="bg-danger flash"><%= flash[:error] %></h4>
    <% end %>
    <!-- end flash messages -->
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<!-- This allows you to edit the post -->
<h1>Edit this Post!</h1>

<%= form_for @post, html: { multipart: true } do |f| %>

	<div>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>

	<div>
		<%= f.label :body %>
		<%= f.text_area :body %>
	</div>

	<div>
		<%= f.label :image %>
		<%= f.file_field :image %>
	</div>

	<%= f.submit "Sumbit these changes!" %>

<% end %>

<%= link_to "Cancel", posts_path %>

app/views/posts/index.html.erb
<!-- This will show all the posts and be the main page -->
<h1>This is the index page for posts</h1>

<ul>
	<% @posts.each do |thread| %>
		<li>
			<%= link_to "#{thread.title}", post_path(thread) %>
			Created <%= time_ago_in_words(thread.created_at) %> ago
		</li>
	<% end %>

	<%= link_to "Add new post!", new_post_path  %>	
</ul>

app/views/posts/new.html.erb
<!-- This is the page to make new posts -->
<h1>New Posts</h1>

<%= form_for @post, html: { multipart: true } do |f| %>

	<div>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>

	<div>
		<%= f.label :body %>
		<%= f.text_area :body %>
	</div>

	<div>
		<%= f.label :image %>
		<%= f.file_field :image %>
	</div>

	<%= f.submit "Add new post!" %>
	<%= link_to "Back to the list!", posts_path %>
<% end %>

app/views/posts/show.html.erb
<!-- This shows the individual post -->
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

<p><%= @post.user.name %></p>

<%= image_tag @post.image.url(:medium)  %>

<% @post.comments.each do |comment| %>
	<div>
		<h4><%= "Comment by #{comment.user.name}" %></h4>
		<p><%= comment.description %></p>
		<p><%= link_to "Delete", delete_comment_path(comment), method: :delete, data: {confirm: "Are you sure"} %></p>
	</div>
<% end %>

<section>
	<h2>Add a new comment!</h2>
		 <%= form_for [@post, @comment] do |f| %> 
		       
	    <div>
	        <%= f.label :description, "Comment", class: "form-label" %> 
	        <%= f.text_area :description, class: "text-area" %>
	    </div>

	    <div>
	        <%= f.submit "Add a comment!", class: "button" %>
	    </div>

	<% end %>
</section>

<%= link_to "Home", posts_path %>
<%= link_to "Edit", edit_post_path %>
<%= link_to "Delete", post_path, method: :delete, data: {confirm: "Are you sure?"} %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
  <%= form_for @user do |f| %>
      
    <% if @user.errors.any? %>
      <div>

        <h4 class="text-danger"><%= pluralize(@user.errors.count, "error") %> prevented you from updating your account:</h4>

        <ul class="list-group">
          <% @user.errors.full_messages.each do |msg| %>   
            <li class="list-group-item list-group-item-danger"><%= msg.downcase %></li>
          <% end %>
        </ul>            

      </div>
    <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <%= f.submit "Update your profile", class: "btn btn-primary" %> | <%= link_to "Home", posts_path, class: "btn btn-primary" %>
  
<% end %>

app/views/users/index.html.erb
<% if logged_in? %>
	<%= "You are currently logged in as: #{current_user.name}" %>
	<%= link_to "Log Out", logout_path, method: :delete %>
<% else %>
	<%= link_to "Log in", login_path %>
	<%= link_to "Sign Up", signup_path %>
<% end %>

<h1>Users</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f|  %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :email %>
		<%= f.text_field :email, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :password %>
		<%= f.password_field :password, class: "form-control" %>
	</div>

	<div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <div>
		<%= f.submit "Sign Up!" %>
	</div>
	
<% end %>